### ISSUE TITLE
Manifest file: No 'version' key

### ISSUE THREAD

**Issue by rgerbranda** [stefanlaheij/ha-buderus#10]
Home Assistant gives the following warning:
No 'version' key in the manifest file for custom integration 'buderus'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'buderus'

**Comment by stefanlaheij** [comment]
Hi,

I recommend you to use this component:
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
Since this component is actively maintained I stopped working on my version.
You can install it through HACS which makes updates also very easy!

Stefan
