### ISSUE TITLE
Still usable as custom integration within Home Assistant 2021.7.3 ?

### ISSUE THREAD

**Issue by marschallphilipp** [stefanlaheij/ha-buderus#12]
When trying to use this custom component I get an error from configuration checker when "buderus:" is not commented out.

"Configuration invalid
Component error: buderus - Integration 'buderus' not found."

I copied the "buderus" folder with the files into the "custom_component" folder and restartet home assistant.
Any help?

Thanks!

**Comment by stefanlaheij** [comment]
Hi,

I recommend you to use this component:
https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
Since this component is actively maintained I stopped working on my version.
You can install it through HACS which makes updates also very easy!

Stefan
