### ISSUE TITLE
Change file locations for Home Assistant 0.88 and above

### ISSUE THREAD

**Issue by tomas-l** [stefanlaheij/ha-buderus#5]
After upgrading to Home Assistant 0.88, the component stopped working. To make it run again, I've had to create custom_components/buderus directory and move files:
```
custom_components/buderus.py         => custom_components/buderus/__init__.py
custom_components/sensor/buderus.py  => custom_components/buderus/sensor.py
custom_components/climate/buderus.py => custom_components/buderus/climate.py
```

**Comment by stefanlaheij** [comment]
Hi @tomas-l ,

Thank you for this information! I changed the filenames.

Stefan
