### ISSUE TITLE
climate type entity missing

### ISSUE THREAD

**Issue by ciechompl** [stefanlaheij/ha-buderus#8]
@stefanlaheij not sure whether this is an issue or just "by design" :) but when I've installed this custom component, I see only sensors but do not see any climate type entity which I could use to set Buderus parameters from HA. 
Is it read only component ? :) or am I doing something wrong ? 

HA: 0.111.4
all 3 files (sensor.py, climate.py, __init__.py) stored in /config/custom_component/buderus folder 

sensors seem to be working correctly 
no errors in log

**Comment by stefanlaheij** [comment]
Hi @ciechompl ,I am not maintaining this component anymore. 
Therefore I would like to point out to you another (actively maintained) custom component: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
It works perfectly!
