### ISSUE TITLE
some sensors are w/o values

### ISSUE THREAD

**Issue by tempo3** [stefanlaheij/ha-buderus#9]
Hi, there are two topic:
1) 2020-07-21 12:37:56 WARNING (MainThread) [homeassistant.components.sensor] Updating buderus sensor took longer than the scheduled update interval 0:00:30

2) some sensors are w/o values, e. g. _boiler_starts, _system_pressure

Hope you can solve the issues, esp. the 2nd with the missing values.
Thx a lot in advance.
Axel

**Comment by stefanlaheij** [comment]
Hi, I am not maintaining this component anymore.
Therefore I would like to point out to you another (actively maintained) custom component: https://github.com/bosch-thermostat/home-assistant-bosch-custom-component
It works perfectly!
